version: "2.3"
services:
  tasty:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    image: tasty
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /opt
    ports:
      - "8889:8888"
    volumes:
      - ${PWD}:/opt
    command: jupyter lab --ip='*' --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''
