version: "2.3"
services:
  tasty:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
    image: tasty
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workdir
    ports:
      - "8888:8888"
    volumes:
      - ${PWD}:/workdir
    command: jupyter lab --ip='*' --port=8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''
